andreve/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_page.urls')),
    path('home/', include('main_page.urls')),
    path('admin/', admin.site.urls)
    
]

main_page/urls.py
from . import views
from django.urls import path

app_name = 'main_page'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login_user'),
    # path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

main_page/models.py
from django.db import models
from django.utils import timezone

# Create your models here. Django default use primary key
class List_Blog(models.Model):
    title = models.CharField(max_length=80,unique=True)
    body = models.CharField(max_length=80,unique=True)
    date_created = models.DateTimeField('date created')

    def __str__(self):
        return self.title

class List_Creator(models.Model):
    id_blog = models.ForeignKey(List_Blog, on_delete=models.CASCADE) # delete all related key
    name = models.CharField(max_length=80)
    def __str__(self):
        return self.name


# class List_Creator(models.Model):
#     id_blog = models.ForeignKey(List_Blog, on_delete=models.CASCADE) # delete all related key
#     name = models.CharField(max_length=80)
#     def __str__(self):
#         return self.name

main_page/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from .models import List_Blog
from django.views import generic
from django.contrib.auth.models import User

from django.contrib import auth

# Create your views here.
# remember you are using generic, you need to only defined, model , template_name, or context_object_name
def home(request):
    context = List_Blog.objects.all()

    return render(request,'main_page/index.html',{'all':context})

def login_user(request):
    if request.POST.get('action')=='post':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if User.objects.filter(username=username).exists():
            return JsonResponse({'is_ok':'0'})
        else:
            # User.objects.create_user(username=username,password=password)
            return JsonResponse({'is_ok':'1'})
    return render(request,'main_page/login.html')


# coba2
# def home(request):
#     context = List_Blog.objects.all()
#     all_context = {}
#     all_context['list_blog'] = context
    # print(context)
    
    # return HttpResponse("You don't have a favorite color.")
    
#     if "session_id" not in request.session:
#         request.session['session_id'] = 1
#     else:
#         request.session['session_id'] += 1
#         if request.session['session_id'] >3:
#             print("Will delete")
#             del request.session['session_id']
#     print("Cookies")
#     print(request.session.keys())
#     print(request.session.items())
#     print(request.COOKIES)

# #     user = User.objects.create_user(username='john',
# # ...                                 email='jlennon@beatles.com',
# # ...                                 password='glass onion')
##      user.save()
#     user = auth.authenticate(username="andreve",password="password")

#     # user.is_staff = True
#     if user.is_authenticated:
#         auth.login(request,user)
#         all_context['username'] = user.username
#         print(request.user.username)
#         print(request.user.is_superuser)
#         auth.logout(request)
#     print(request.user.is_anonymous)
    # for field in User._meta.fields:
    #     print(field.name)
    # print(User.objects.filter(username=user))
    
    # print(request.session.set_test_cookie())
    # print(request.session.test_cookie_worked())
    # print(request.session.delete_test_cookie())

    
    
    
    # print("Session")
    # print(request.session.keys())

    # return render(request,'main_page/index.html',all_context)
    # return render(request,'main_page/index.html',{'all':context})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/main_page/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main_page/style.css' %}">
    <title>hehe</title>

</head>
<body>
    <div class='header'>
        <label>ANDREVE</label> &#9 <a class='list-menu-content'>Home</a> <a class='list-menu-content'>About</a>
    </div>

<content>

    {% for blog in list_blog %}
        <li>{{ blog.title }}</li>
    {% endfor %}

    <a>{{request.path}}</a>

<div class="grid-container">
    <div class="grid-item">1</div>
    <div class="grid-item">2</div>
    <div class="grid-item">3</div>  
    <div class="grid-item">4</div>
    <div class="grid-item">5</div>
    <div class="grid-item">6</div>  
    <div class="grid-item">7</div>
    <div class="grid-item">8</div>
    <div class="grid-item">9</div>  
</div>
</content>
</body>
</html>

templates/main_page/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
</head>
<body>
    <form method="POST" id="post-form">
        {% csrf_token %}
        <div class="form-group">
          <label>Username</label>
          <input type="text" class="form-control" id="username" placeholder="Username">
        </div>
         <div class="form-group">
           <label>Password</label>
           <input class="form-control" id="password" placeholder="Password">
         </div>
         <button type="submit" class="btn btn-primary" id='button-form'>Submit</button>
      </form>
      <div class="response">
          <a class="response_text"></a>
      </div>


      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script>
            $("#button-form").click(function(event){
                event.preventDefault()
                $.ajax({
                    type:"POST",
                    url:"{% url 'main_page:login_user' %}",
                    data:{
                        username:$("#username").val(),
                        password:$("#password").val(),
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                        action: 'post'
                    },
                    success:function(json){
                        if (json['is_ok']=='0'){
                            $(".response_text").text("Username is taken!")
                        } else if (json['is_ok']=='1'){
                            $(".response_text").text("SUCCESS!")
                        }
                    },
                    error : function(xhr,errmsg,err) {
                            console.log(xhr.status + ": " + xhr.responseText);
                    }
                })

            })


      </script>
</body>
</html>